library(datasets)
powerDF = read.table("household_power_consumption.txt", skip=66637, nrows=2880, sep=";")
featureLabelsVector = c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
colnames(powerDF) = featureLabelsVector
powerDF_plot3 = tbl_df(powerDF)
powerDF_plot3$Time = as.character(powerDF_plot3$Time)
powerDF_plot3$Date = as.character(powerDF_plot3$Date)
powerDF_plot3$DateTime <- as.POSIXct(paste( powerDF_plot3$Date,  powerDF_plot3$Time), format="%d/%m/%Y %H:%M:%S")
plot(powerDF_plot3$DateTime, powerDF_plot3$Sub_metering_1, xlab = "", ylab="Energy sub metering", type="l", col="black")
lines(powerDF_plot3$DateTime,powerDF_plot3$Sub_metering_2, type="l", col="red")
lines(powerDF_plot3$DateTime,powerDF_plot3$Sub_metering_3, type="l", col="blue")
legend("topright", lty=1, col = c("black","red","blue"), legend= c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.copy(png, file = "plot3.png")
dev.off()
