library(datasets)
powerDF = read.table("household_power_consumption.txt", skip=66637, nrows=2880, sep=";")
featureLabelsVector = c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
colnames(powerDF) = featureLabelsVector
powerDF_plot4 = tbl_df(powerDF)
powerDF_plot4$Time = as.character(powerDF_plot4$Time)
powerDF_plot4$Date = as.character(powerDF_plot4$Date)
powerDF_plot4$DateTime <- as.POSIXct(paste( powerDF_plot4$Date,  powerDF_plot4$Time), format="%d/%m/%Y %H:%M:%S")
plot(powerDF_plot3$DateTime, powerDF_plot3$Sub_metering_1, xlab = "", ylab="Energy sub metering", type="l", col="black")
lines(powerDF_plot3$DateTime,powerDF_plot3$Sub_metering_2, type="l", col="red")
lines(powerDF_plot3$DateTime,powerDF_plot3$Sub_metering_3, type="l", col="blue")
legend("topright", lty=1, col = c("black","red","blue"), legend= c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
par(mfrow = c(2,2))
with(powerDF_plot4, {
  plot(DateTime,Global_active_power, xlab="", ylab="Global Active Power", type="l") 
  plot(DateTime,Voltage, xlab="datetime", type="l") 
  plot(DateTime, Sub_metering_1, xlab = "", ylab="Energy sub metering", type="l", col="black") 
  lines(DateTime,Sub_metering_2, type="l", col="red") 
  lines(DateTime,Sub_metering_3, type="l", col="blue") 
  legend("topright", lty=1, cex=0.8, bty="n", col = c("black","red","blue"), legend= c("Sub_metering_1","Sub_metering_2","Sub_metering_3")) 
  plot(DateTime,Global_reactive_power, xlab="datetime", type="l")})
dev.copy(png, file = "plot4.png")
dev.off()
